### ISSUE TITLE
Задание выполнено

### ISSUE THREAD

**Issue by Sefferever** [MIEE-ACS/domashnee-zadanie-no3-Sefferever#1]
Вариант №11 (Евдокимов) на проверку

**Comment by d-makarenko** [comment]
Правильный ответ всегда первый, весь смысл программы пропадает. 
Что можно было сделать, чтобы правильный ответ был на случайном месте:
1. Добавить глобальную переменную, которая хранит номер радио кнопки с правильным ответом.
2. При создании нового вопроса, в эту переменную записывать случайное число от 0 до 3
3. Через switch записать правильный ответ в соответствующую радио кнопку 
4. При проверке через switch проверять, что была выбрана правильная кнопка

Звучит сложно, но на самом деле все довольно просто, пара десятков строчек

2/4
